name: BasicAnarchy
version: 1.0.0
api-version: 1.15
author: VoxFall
website: http://www.timecraft-mc.net/

main: com.owenselles.basicanarchy.BasicAnarchy

commands:
  suicide:
    description: Kill yourself
    usage: /suicide
  help:
    description: Get command information
    usage: /help